apiVersion: apps/v1
kind: Deployment
metadata:
  name: social-media-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: social-media-backend
  template:
    metadata:
      labels:
        app: social-media-backend
    spec:
      containers:
      - name: social-media-backend
        image: gcr.io/[PROJECT-ID]/social-media-backend
        ports:
        - containerPort: 3000
        env:
        - name: MONGODB_URI
          value: "mongodb+srv://<username>:<password>@cluster0.mongodb.net/socialmedia?retryWrites=true&w=majority"
        - name: PORT
          value: "3000"