apiVersion: apps/v1
kind: Deployment
metadata:
  name: social-media-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: social-media-backend
  template:
    metadata:
      labels:
        app: social-media-backend
    spec:
      containers:
      - name: social-media-backend
        image: aeki53/social-media-backend:latest
        ports:
        - containerPort: 3000
        env:
        - name: MONGODB_URI
          value: "mongodb+srv://group_4:final%40project@web-project.paf8p.mongodb.net/?retryWrites=true&w=majority&appName=web-project"
        - name: PORT
          value: "3000"